### ISSUE TITLE
Error with logrotate

### ISSUE THREAD

**Issue by przemekjagielski** [ovh/noderig#73] opened 2020-05-30 11:09 UTC
Hello, 
Todays i reconfigure all configfile in logrotate. I checked one of my server in OVH, about logrotate service and in log file, i see this:
`# service logrotate status
● logrotate.service - Rotate log files
   Loaded: loaded (/lib/systemd/system/logrotate.service; static; vendor preset: enabled)
   Active: inactive (dead) since Sat 2020-05-30 13:09:14 CEST; 2s ago
     Docs: man:logrotate(8)
           man:logrotate.conf(5)
  Process: 8206 ExecStart=/usr/sbin/logrotate /etc/logrotate.conf (code=exited, status=0/SUCCESS)
 Main PID: 8206 (code=exited, status=0/SUCCESS)

May 30 13:09:14 mon systemd[1]: Starting Rotate log files...
May 30 13:09:14 mon logrotate[8206]: error: Ignoring noderig because the file owner is wrong (should be root or user with uid 0).
May 30 13:09:14 mon systemd[1]: logrotate.service: Succeeded.
May 30 13:09:14 mon systemd[1]: Started Rotate log files.`

Can you review this and repair in next update?

**Comment by aurrelhebert** [comment] 2020-07-22 12:55
Hi @przemekjagielski, coud you details us how noderig was installed and on which OS? Thanks

**Comment by JaapD** [comment] 2020-09-21 14:11
I have the same problem. Noderig was installed when I rent the server.
Every now and then the owner of the file /etc/logrotate.d/noderig becomes noderig:noderig. Probably after an update?
When I change it by hand to root:root and the problem is over.

**Comment by aurrelhebert** [comment] 2020-10-01 13:46
Indeed, we found trace of this specific bug only on Debian OS. It should be fixed with the 2.5.7 release.
Thanks for reported it

**Closed by aurrelhebert** 2020-10-01 13:46 UTC
